@startuml 構成図
left to right direction

rectangle ブラウザ as browser

rectangle container-app as containerApp {
  component コンテナ画面 as containerPage
}
note right: port=8080

rectangle a-service as aService {
  component "a-component" as aComponent
}
note right: port=8081

rectangle b-service as bService {
  component "b-component" as bComponent
}
note right: port=8082

browser -- containerPage
browser -- aComponent
browser -- bComponent
@enduml

@startuml シーケンス図
participant ブラウザ as browser
participant コンテナ画面 as containerPage
participant "container-app" as containerApp
participant "a-service" as aService
participant "b-service" as bService

browser -> containerApp : 画面をリクエスト
containerApp -> containerApp : リクエスト内容に応じてHTMLを組み立てる
containerApp -> browser : HTMLを返却
create containerPage
browser -> containerPage : 表示

group a-componentの描画
browser -> aService : asset-manifest.jsonを取得
return
browser -> aService : asset-manifest.json内の'main.js'を取得
return
browser -> containerPage : render関数を実行してコンポーネントを表示
end

group b-componentの描画
browser -> bService : asset-manifest.jsonを取得
return
browser -> bService : asset-manifest.json内の'main.js'を取得
return
browser -> containerPage : render関数を実行してコンポーネントを表示
end
@enduml